replicaCount: 1

config:
  openapiKey: ""

image:
  repository: nikitosnik/chatbot-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: chat.yoursite.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: chat-yoursite-com-tls
      hosts:
        - chat.yoursite.com

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
